# Generated by Django 3.2.7 on 2021-10-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_following_posts_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='reply',
        ),
    ]
