# Generated by Django 3.2.9 on 2021-12-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
