# Generated by Django 3.2.9 on 2021-12-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_posts_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='liked',
            new_name='likes',
        ),
    ]
