# Generated by Django 3.2.9 on 2021-12-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20211210_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_follower',
            new_name='user_following',
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user', 'user_following', 'post')},
        ),
    ]
