# Generated by Django 3.2.9 on 2021-12-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user', 'user_following')},
        ),
        migrations.RemoveField(
            model_name='following',
            name='post',
        ),
    ]
