# Generated by Django 3.2.9 on 2021-12-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20211212_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='user_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='network.userprofile'),
        ),
    ]
